frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

infra:
  - changed-files:
      - any-glob-to-any-file: 'infra/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '.github/**'
