export const TRADERS = [
  {
    rank: 1,
    id: 'alpha',
    nameKr: '알파',
    strategy: 'momentum_kr',
    strategyDesc: '국내 주식 모멘텀 추종',
    assetType: 'stock_kr',
    isSimulated: true,
    stats: {
      totalReturn: 0.0213,
      totalReturnAmount: 213000,
      winRate: 0.68,
      totalTrades: 47,
      portfolioValue: 10213000,
      maxDrawdown: 0.032,
      sharpeRatio: 1.42,
    },
  },
  {
    rank: 2,
    id: 'beta',
    nameKr: '베타',
    strategy: 'contrarian_crypto',
    strategyDesc: '코인 역추세 전략',
    assetType: 'crypto',
    isSimulated: true,
    stats: {
      totalReturn: 0.0187,
      totalReturnAmount: 187000,
      winRate: 0.62,
      totalTrades: 52,
      portfolioValue: 10187000,
      maxDrawdown: 0.045,
      sharpeRatio: 1.21,
    },
  },
  {
    rank: 3,
    id: 'gamma',
    nameKr: '감마',
    strategy: 'quant_us',
    strategyDesc: '미국 주식 퀀트',
    assetType: 'stock_us',
    isSimulated: true,
    stats: {
      totalReturn: 0.0156,
      totalReturnAmount: 156000,
      winRate: 0.71,
      totalTrades: 38,
      portfolioValue: 10156000,
      maxDrawdown: 0.028,
      sharpeRatio: 1.58,
    },
  },
  {
    rank: 4,
    id: 'delta',
    nameKr: '델타',
    strategy: 'etf_allocation',
    strategyDesc: 'ETF 자산배분',
    assetType: 'stock_kr',
    isSimulated: true,
    stats: {
      totalReturn: 0.0098,
      totalReturnAmount: 98000,
      winRate: 0.74,
      totalTrades: 24,
      portfolioValue: 10098000,
      maxDrawdown: 0.018,
      sharpeRatio: 1.73,
    },
  },
  {
    rank: 5,
    id: 'epsilon',
    nameKr: '엡실론',
    strategy: 'crossasset_arb',
    strategyDesc: '크로스에셋 차익거래',
    assetType: 'stock_kr',
    isSimulated: true,
    stats: {
      totalReturn: 0.0071,
      totalReturnAmount: 71000,
      winRate: 0.59,
      totalTrades: 61,
      portfolioValue: 10071000,
      maxDrawdown: 0.052,
      sharpeRatio: 1.08,
    },
  },
]
